#########################################
########## Cadastro de Usuário ##########
POST /api/register HTTP/1.1
Host: localhost:4000
Content-Type: application/json

{
    "user": {
        "email": "williamjager.dev@gmail.com",
        "name": "William Jäger"
    }
}

#########################################
########## Cadastro de Sorteio ##########
POST /api/raffles HTTP/1.1
Host: localhost:4000
Content-Type: application/json

{
    "raffle": {
        "name": "Loto Elixir 2",
        "date": "2022-12-26"
    }
}

#########################################
########## Cadastro no Sorteio ##########
POST /api/subscribe-raffle HTTP/1.1
Host: localhost:4000
Content-Type: application/json

{
    "subscribe": {
        "user_id": "64ead584-c15b-4b2a-a65a-ed3fbcd1210b",
        "raffle_id": "dc053560-dd54-4993-84b8-78fb3ed3bc85"
    }
}

########################################
########## Consultar Vencedor ##########
GET /api/winner/dc053560-dd54-4993-84b8-78fb3ed3bc85 HTTP/1.1
Host: localhost:4000